init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node 6.9.2 x64
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
build_script:
  - ps: .\run.ps1 default-build
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
os: Visual Studio 2017
