init:
  - git config --global core.autocrlf true
install:
   - ps: Install-Product node 8 x64
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
build_script:
  - ps: .\build.ps1 /t:Build /t:TestTemplates
artifacts:
  - path: .\artifacts\build\*.nupkg
    type: NuGetPackage
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
os: Visual Studio 2017
on_finish :
  - ps: Pop-Location
  # After running tests, upload results to Appveyor
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\tmp\junit\*.xml))
deploy: off
test: off
